version: '3.7'

services:
  db:
    image: postgres:14-alpine

    volumes:
      - ~/dbs/javaTicTacToe/data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: test

    ports:
      - "5432:5432"
